description: Learning to ask

auth:
  vc: msrlabs
  cluster: eu1
  docker_repo: philly/jobs/custom/generic-docker
  docker_tag: py27
  azure_config:
    storage_account_name: kxnguyen
    container_name: learningtoask

code:
  local_dir: $CONFIG_DIR/code

data:
  data_upload: False
  #local_dir: data
  remote_dir: data/learningtoask/v2_7

jobs:
- name: verbal_1_step_find_object
  entry_point: tasks/R2R/train_find_object.py
  n_gpu: 1
  args: "-config configs/intent_step_by_step_find_obj_cov.json -n_subgoal_steps 1"


