description: Learning to ask

auth:
  vc: msrlabs
  cluster: eu1
  docker_repo: philly/jobs/custom/generic-docker
  docker_tag: py27
  azure_config:
    storage_account_name: kxnguyen
    container_name: learningtoask

code:
  local_dir: $CONFIG_DIR/code

data:
  data_upload: False
  #local_dir: data
  remote_dir: data/learningtoask

jobs:
- name: oracle_ask_deviate_2_0
  entry_point: tasks/R2R/train.py
  n_gpu: 1
  args: "-config configs/intent_next_optimal.json -nav_feedback sample -ask_first True -oracle_ask True -deviate_threshold 2.0  -exp_name intent_next_optimal_tune_oracle"
- name: oracle_ask_deviate_3_0
  entry_point: tasks/R2R/train.py
  n_gpu: 1
  args: "-config configs/intent_next_optimal.json -nav_feedback sample -ask_first True -oracle_ask True -deviate_threshold 2.0  -exp_name intent_next_optimal_tune_oracle"
- name: oracle_ask_deviate_5_0
  entry_point: tasks/R2R/train.py
  n_gpu: 1
  args: "-config configs/intent_next_optimal.json -nav_feedback sample -ask_first True -oracle_ask True -deviate_threshold 5.0  -exp_name intent_next_optimal_tune_oracle"
- name: oracle_ask_deviate_3_0_uncertain_1_2
  entry_point: tasks/R2R/train.py
  n_gpu: 1
  args: "-config configs/intent_next_optimal.json -nav_feedback sample -ask_first True -oracle_ask True -deviate_threshold 3.0 -uncertain_threshold 1.2  -exp_name intent_next_optimal_tune_oracle"
- name: oracle_ask_deviate_3_0_uncertain_1_0
  entry_point: tasks/R2R/train.py
  n_gpu: 1
  args: "-config configs/intent_next_optimal.json -nav_feedback sample -ask_first True -oracle_ask True -deviate_threshold 3.0 -uncertain_threshold 1.0  -exp_name intent_next_optimal_tune_oracle"
- name: oracle_ask_deviate_3_0_uncertain_0_8
  entry_point: tasks/R2R/train.py
  n_gpu: 1
  args: "-config configs/intent_next_optimal.json -nav_feedback sample -ask_first True -oracle_ask True -deviate_threshold 3.0 -uncertain_threshold 0.8  -exp_name intent_next_optimal_tune_oracle"
- name: oracle_ask_deviate_3_0_uncertain_1_2_unmoved_5
  entry_point: tasks/R2R/train.py
  n_gpu: 1
  args: "-config configs/intent_next_optimal.json -nav_feedback sample -ask_first True -oracle_ask True -deviate_threshold 3.0 -uncertain_threshold 1.2 -unmoved_threshold 5  -exp_name intent_next_optimal_tune_oracle"
- name: oracle_ask_deviate_3_0_uncertain_1_2_unmoved_7
  entry_point: tasks/R2R/train.py
  n_gpu: 1
  args: "-config configs/intent_next_optimal.json -nav_feedback sample -ask_first True -oracle_ask True -deviate_threshold 3.0 -uncertain_threshold 1.2 -unmoved_threshold 7  -exp_name intent_next_optimal_tune_oracle"
- name: oracle_ask_deviate_3_0_uncertain_1_2_unmoved_9
  entry_point: tasks/R2R/train.py
  n_gpu: 1
  args: "-config configs/intent_next_optimal.json -nav_feedback sample -ask_first True -oracle_ask True -deviate_threshold 3.0 -uncertain_threshold 1.2 -unmoved_threshold 9  -exp_name intent_next_optimal_tune_oracle"
