description: VNLA aggrevate experiments 20 seeds continue 94798 long
# experiment named vnla_time_comparisons

target:
  # which virtual cluster you belong to (msrlabs, etc.). Everyone has access to "msrlabs".
  vc: msrlabs
  # physical cluster to use (cam, gcr, rr1, rr2) or Azure clusters (eu1, eu2, etc.)
  cluster: eu1

environment:
  image: philly/jobs/test/pytorch:pytorch1.2.0-py36-mattersim
  registry: phillyregistry.azurecr.io

  setup:
    - pip install scikit-learn --user
    - python -m pip install networkx==2.3 --user
    - CUDA_VISIBLE_DEVICES=0
    - pip install tensorboard --user
    # - CUDA_VISIBLE_DEVICES=0,1,2,3
    # - pip install ipdb --user

storage:
  input1:
    storage_account_name: msrairesidentssa4
    container_name: matterport3d
    mount_dir: /mnt/matterport3d
    # local_dir: /home/hoyeung/blob_matterport3d/
  output:
    storage_account_name: msrairesidentssa4
    container_name: experiment-results
    mount_dir: /mnt/experiment-results-philly/
    # local_dir: /home/hoyeung/blob_experiments/

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

# data:
#   data upload is not required for this example

# seed list
# 10 [42, 677, 848, 163, 620, 511, 102, 158, 2, 204]
# 20 + [471, 154, 220, 748, 623, 47, 882, 136, 315, 48]

# list of jobs to run, we run 2 jobs in this example
jobs:
  # name must be unique across the jobs
- name: data_94798_seed_42_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_42_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 42 -start_beta 0.0
- name: data_94798_seed_677_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_677_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 677 -start_beta 0.0
- name: data_94798_seed_848_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_848_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 848 -start_beta 0.0
- name: data_94798_seed_163_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_163_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 163 -start_beta 0.0
- name: data_94798_seed_620_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_620_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 620 -start_beta 0.0
- name: data_94798_seed_511_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_511_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 511 -start_beta 0.0
- name: data_94798_seed_102_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_102_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 102 -start_beta 0.0
- name: data_94798_seed_158_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_158_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 158 -start_beta 0.0
- name: data_94798_seed_2_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_2_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 2 -start_beta 0.0
- name: data_94798_seed_204_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_204_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 204 -start_beta 0.0
- name: data_94798_seed_471_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_471_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 471 -start_beta 0.0
- name: data_94798_seed_154_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_154_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 154 -start_beta 0.0
- name: data_94798_seed_220_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_220_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 220 -start_beta 0.0
- name: data_94798_seed_748_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_748_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 748 -start_beta 0.0
- name: data_94798_seed_623_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_623_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 623 -start_beta 0.0
- name: data_94798_seed_47_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_47_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 47 -start_beta 0.0
- name: data_94798_seed_882_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_882_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 882 -start_beta 0.0
- name: data_94798_seed_136_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_136_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 136 -start_beta 0.0
- name: data_94798_seed_315_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_315_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 315 -start_beta 0.0
- name: data_94798_seed_48_long
  sku: G1
  command:
  - cd tasks/VNLA/scripts/ && bash train_experiments.sh "20200125_philly_aggrevate_seeds" "data_94798_seed_48_long" "configs/experiment.json" -batch_size 100 -start_beta_decay 100 -decay_beta_every 100 -min_history_to_learn 1000 -save_every 1000 -log_every 1000 -plot_to_philly 0 -data_suffix original -dropout_ratio 0.5 -agent_end_criteria 2.5 -n_iters 100000 -seed 48 -start_beta 0.0